name: Production Release (test)

on:
  push:
    branches: [ prod ]
  workflow_dispatch:

permissions:                                   # top-level defaults
  contents: write
  deployments: write
  id-token: write
  pull-requests: write
  issues: write

# top-level orchestrator (excerpt)

jobs:
  auto-approve:
    uses: ./.github/workflows/prod-auto-approve.yml   # see step 3
    with:
      run_id: ${{ github.run_id }}
      auto_env: tc-prod                               # approve only this env
    secrets:
      GH_PAT: ${{ secrets.DEPLOY_BOT_PAT }}

  # ──────────────────────────────────────────────────────────────
  build:
    uses: ./.github/workflows/prod-build.yml
    with:
      environment: tc-prod-review        # ←   manual
    needs: auto-approve

  test:
    needs: [build]
    uses: ./.github/workflows/prod-test.yml
    with:
      environment: tc-prod               # ←   auto

  deploy:
    needs: test
    uses: ./.github/workflows/prod-deploy.yml
    with:
      environment: tc-prod        # ←   manual

